### ISSUE TITLE
injectThemePath should filter all html files

### ISSUE THREAD

**Issue by renfeng** [oracle/oraclejet-tooling#3]

**Comment by peppertech** [comment]
Can you please provide more details about what you are looking for with this?  What is the use case?

**Comment by renfeng** [comment]
Here, the method, injectThemePath, only works on ${paths.staging.stagingPath}/index.html.
https://github.com/oracle/oraclejet-tooling/blob/12b305e/lib/indexHtmlInjector.js#L188

It should scan all html files recursively under ${paths.staging.stagingPath}.
